export enum ActionTypeArtDetails {
  ART_DETAILS_REQUEST = "ART_DETAILS_REQUEST",
  ART_DETAILS_SUCCESS = "ART_DETAILS_SUCCESS",
  ART_DETAILS_FAIL = "ART_DETAILS_FAIL",
  ART_DETAILS_CLEAR = "ART_DETAILS_CLEAR",

}
