export enum ActionTypeArts {
  ART_LIST_REQUEST = "ART_LIST_REQUEST",
  ART_LIST_SUCCESS = "ART_LIST_SUCCESS",
  ART_LIST_FAIL = "ART_LIST_FAIL",
  ART_DELTE_ITEM = "ART_DELTE_ITEM",
  ART_DELTE_ITEM_FAIL = "ART_DELTE_ITEM_FAIL",

}
