export enum ActionTypeUser {
  USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST",
  USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL",

  CURRENT_USER = "CURRENT_USER",
}
